#!/usr/bin/env python
#MUST BE RUN USING PYTHON3

#This script demonstrates tweeting if some condition is met.
#In this case, if it generates a random number <= 5, tweet that number.
import sys
import random

#Import the Twython package
from twython import Twython

#Import the authentication information from auth.py
from auth import (
        conKey,
        conSec,
        accTok,
        accSec
)

#Generate a random number
tweetStr=random.uniform(0,10)

#Create an instance of Twython with the authentication information
api=Twython(conKey,conSec,accTok,accSec)

#If the random number generated is <= 5
if (tweetStr <= 5):
    #Tweet and print the tweet
    api.update_status(status=tweetStr)
    print(tweetStr)
else:
    #Print that nothing was tweeted
    print("Nothing tweeted.")
